<?php

/**
 * @file
 * Allows saving of domain specific configuration through the UI.
 */

/**
 * Implements hook_preprocess_page().
 */
function domain_config_ui_preprocess_page(&$variables) {
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);
  $has_permissions = \Drupal::currentUser()->hasPermission('access domain config widget');

  if ($is_admin && $has_permissions) {
    $form = \Drupal::formBuilder()->getForm('Drupal\domain_config_ui\Form\SwitchForm', \Drupal::request());
    $variables['page']['content']['domain_config_ui_switch'] = $form;
  }
}
