services:
  domain_config_ui.manager:
    class: Drupal\domain_config_ui\DomainConfigUIManager
    arguments: ['@request_stack']

  domain_config_ui.factory:
    class: Drupal\domain_config_ui\Config\ConfigFactory
    decorates: config.factory
    decoration_priority: 1
    tags:
      - { name: event_subscriber }
      - { name: service_collector, tag: 'config.factory.override', call: addOverride }
    arguments: ['@config.storage', '@event_dispatcher', '@config.typed', '@domain_config_ui.manager']
